services:
  app:
    image: drill_yuqin_base:latest
    container_name: drill_yuqin
    restart: always
    volumes:
      - .:/app
    ports:
      - "6895:6895"
    env_file:
      - config/.env
    environment:
      - PYTHONPATH=/app
    command: ./start.sh
    networks:
      - platform-net

    depends_on:
      - redis

  mysql:
    image: mysql:8.3.0
    container_name: mysql8

    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - platform-net
    command: --default-authentication-plugin=mysql_native_password


  redis:
    image: redis:latest
    container_name: yuqin_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - platform-net



  web_unit:
    image: nginx:latest
    container_name: web-unit
    ports:
      - "8090:8090"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./yuqing_front:/opt/yuqing
    networks:
      platform-net:
    restart: always

volumes:
  mysql_data:
  redis_data:

networks:
  platform-net:
    external: true