"""创建关联信息

Revision ID: 075c38938a3b
Revises: c170ea8e0e8f
Create Date: 2024-12-24 10:47:47.462047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075c38938a3b'
down_revision: Union[str, None] = 'c170ea8e0e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'exercise_rooms', 'events', ['event_mid'], ['mid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_rooms', type_='foreignkey')
    # ### end Alembic commands ###
