"""create_corpus

Revision ID: 0c8a5536f1e1
Revises: 5691215ecc70
Create Date: 2024-12-23 16:39:29.278660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c8a5536f1e1'
down_revision: Union[str, None] = '5691215ecc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corpus', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('corpus', sa.Column('upload_id', sa.String(length=255), nullable=False))
    op.add_column('corpus', sa.Column('file_data', sa.Text(), nullable=True, comment='语料内容'))
    op.create_index(op.f('ix_corpus_file_name'), 'corpus', ['file_name'], unique=False)
    op.create_index(op.f('ix_corpus_upload_id'), 'corpus', ['upload_id'], unique=False)
    op.drop_column('corpus', 'notes')
    op.drop_column('corpus', 'content')
    op.drop_column('corpus', 'severity')
    op.drop_column('corpus', 'speech_type')
    op.drop_column('corpus', 'scenario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corpus', sa.Column('scenario', mysql.VARCHAR(length=100), nullable=True, comment='出现场景'))
    op.add_column('corpus', sa.Column('speech_type', mysql.VARCHAR(length=50), nullable=True, comment='言论类型/情绪化表达'))
    op.add_column('corpus', sa.Column('severity', mysql.INTEGER(), autoincrement=False, nullable=True, comment='严重程度'))
    op.add_column('corpus', sa.Column('content', mysql.TEXT(), nullable=True, comment='语料内容'))
    op.add_column('corpus', sa.Column('notes', mysql.TEXT(), nullable=True, comment='备注'))
    op.drop_index(op.f('ix_corpus_upload_id'), table_name='corpus')
    op.drop_index(op.f('ix_corpus_file_name'), table_name='corpus')
    op.drop_column('corpus', 'file_data')
    op.drop_column('corpus', 'upload_id')
    op.drop_column('corpus', 'file_name')
    # ### end Alembic commands ###
