"""create_corpus

Revision ID: 5a578d030804
Revises: 44b72275b4e7
Create Date: 2024-12-23 14:10:16.139025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a578d030804'
down_revision: Union[str, None] = '44b72275b4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('file_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_files_id'), 'corpus_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corpus_files_id'), table_name='corpus_files')
    op.drop_table('corpus_files')
    # ### end Alembic commands ###
