"""create_corpus

Revision ID: 5ab07093a1ac
Revises: 5a578d030804
Create Date: 2024-12-23 16:09:22.609919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ab07093a1ac'
down_revision: Union[str, None] = '5a578d030804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True, comment='语料内容'),
    sa.Column('speech_type', sa.String(length=50), nullable=True, comment='言论类型/情绪化表达'),
    sa.Column('severity', sa.Integer(), nullable=True, comment='严重程度'),
    sa.Column('scenario', sa.String(length=100), nullable=True, comment='出现场景'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('deduction', sa.Integer(), nullable=True, comment='扣分'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_id'), 'corpus', ['id'], unique=False)
    op.drop_index('ix_corpus_files_id', table_name='corpus_files')
    op.drop_table('corpus_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_files',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('uploader_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_time', mysql.DATETIME(), nullable=True),
    sa.Column('file_data', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.user_id'], name='corpus_files_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_corpus_files_id', 'corpus_files', ['id'], unique=False)
    op.drop_index(op.f('ix_corpus_id'), table_name='corpus')
    op.drop_table('corpus')
    # ### end Alembic commands ###
