"""add_opentions

Revision ID: 8cab0d0aa3bd
Revises: 
Create Date: 2024-12-13 14:16:23.008313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cab0d0aa3bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('mid', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('personal_href', sa.Text(), nullable=True),
    sa.Column('event_source', sa.String(length=255), nullable=True),
    sa.Column('content_show', sa.Text(), nullable=True),
    sa.Column('content_all', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=255), nullable=True),
    sa.Column('event_heat', sa.Integer(), nullable=True),
    sa.Column('original_heat', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.Column('comment_num', sa.Integer(), nullable=True),
    sa.Column('star_num', sa.Integer(), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_index(op.f('ix_events_event_source'), 'events', ['event_source'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_mid'), 'events', ['mid'], unique=False)
    op.create_index(op.f('ix_events_nickname'), 'events', ['nickname'], unique=False)
    op.create_index(op.f('ix_events_publish_time'), 'events', ['publish_time'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_index(op.f('ix_events_uid'), 'events', ['uid'], unique=False)
    op.create_table('real_events',
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('real_mid', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('content_show', sa.Text(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('event_heat', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('real_mid')
    )
    op.create_index(op.f('ix_real_events_nickname'), 'real_events', ['nickname'], unique=False)
    op.create_index(op.f('ix_real_events_publish_time'), 'real_events', ['publish_time'], unique=False)
    op.create_index(op.f('ix_real_events_real_mid'), 'real_events', ['real_mid'], unique=False)
    op.create_index(op.f('ix_real_events_room_id'), 'real_events', ['room_id'], unique=False)
    op.create_index(op.f('ix_real_events_title'), 'real_events', ['title'], unique=False)
    op.create_table('school_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_name_id'), 'school_name', ['id'], unique=False)
    op.create_index(op.f('ix_school_name_name'), 'school_name', ['name'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('events_temp',
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mid', sa.BigInteger(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('personal_href', sa.Text(), nullable=True),
    sa.Column('event_source', sa.String(length=255), nullable=True),
    sa.Column('content_show', sa.Text(), nullable=True),
    sa.Column('content_all', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=255), nullable=True),
    sa.Column('event_heat', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.Column('heat_change', sa.JSON(), nullable=True),
    sa.Column('comment_num', sa.Integer(), nullable=True),
    sa.Column('star_num', sa.Integer(), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('event_bg', sa.JSON(), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=True),
    sa.Column('release', sa.JSON(), nullable=True),
    sa.Column('post_rating', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_events_temp_create_time'), 'events_temp', ['create_time'], unique=False)
    op.create_index(op.f('ix_events_temp_event_source'), 'events_temp', ['event_source'], unique=False)
    op.create_index(op.f('ix_events_temp_event_type'), 'events_temp', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_temp_mid'), 'events_temp', ['mid'], unique=False)
    op.create_index(op.f('ix_events_temp_nickname'), 'events_temp', ['nickname'], unique=False)
    op.create_index(op.f('ix_events_temp_publish_time'), 'events_temp', ['publish_time'], unique=False)
    op.create_index(op.f('ix_events_temp_room_id'), 'events_temp', ['room_id'], unique=False)
    op.create_index(op.f('ix_events_temp_title'), 'events_temp', ['title'], unique=False)
    op.create_index(op.f('ix_events_temp_uid'), 'events_temp', ['uid'], unique=False)
    op.create_table('exercise_rooms',
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('marksman_num', sa.Integer(), nullable=False),
    sa.Column('person_num', sa.Integer(), nullable=True),
    sa.Column('rating_keywords', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('invite_code', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_exercise_rooms_invite_code'), 'exercise_rooms', ['invite_code'], unique=True)
    op.create_index(op.f('ix_exercise_rooms_room_id'), 'exercise_rooms', ['room_id'], unique=False)
    op.create_table('opinions',
    sa.Column('main_body_mid', sa.BigInteger(), nullable=True),
    sa.Column('main_comment_mid', sa.BigInteger(), nullable=False),
    sa.Column('parent_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('process_content', sa.Text(), nullable=True),
    sa.Column('native_content', sa.Text(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('replies_count', sa.Integer(), nullable=True),
    sa.Column('comment_heat', sa.Integer(), nullable=True),
    sa.Column('comment_original_heat', sa.Integer(), nullable=True),
    sa.Column('comment_location', sa.String(length=255), nullable=True),
    sa.Column('star_num', sa.Integer(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('sentiment', sa.Enum('NEGATIVE', 'NEUTRAL', 'POSITIVE', name='sentiment'), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['main_body_mid'], ['events.mid'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['opinions.main_comment_mid'], ),
    sa.PrimaryKeyConstraint('main_comment_mid')
    )
    op.create_index(op.f('ix_opinions_comment_location'), 'opinions', ['comment_location'], unique=False)
    op.create_index(op.f('ix_opinions_main_comment_mid'), 'opinions', ['main_comment_mid'], unique=False)
    op.create_index(op.f('ix_opinions_nickname'), 'opinions', ['nickname'], unique=False)
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_tokens_token_hash'), 'tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_tokens_token_id'), 'tokens', ['token_id'], unique=False)
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('completions', sa.Integer(), nullable=False),
    sa.Column('score', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userinfo_id'), 'userinfo', ['id'], unique=False)
    op.create_table('history_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['events_temp.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'room_id')
    )
    op.create_index(op.f('ix_history_info_id'), 'history_info', ['id'], unique=False)
    op.create_table('opinions_temp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_body_mid', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.String(length=255), nullable=True),
    sa.Column('main_comment_mid', sa.BigInteger(), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('process_content', sa.Text(), nullable=True),
    sa.Column('native_content', sa.Text(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('replies_count', sa.Integer(), nullable=True),
    sa.Column('comment_heat', sa.Integer(), nullable=True),
    sa.Column('comment_location', sa.String(length=255), nullable=True),
    sa.Column('star_num', sa.Integer(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('sentiment', sa.String(length=255), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_body_mid'], ['events_temp.mid'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['opinions_temp.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opinions_temp_comment_location'), 'opinions_temp', ['comment_location'], unique=False)
    op.create_index(op.f('ix_opinions_temp_id'), 'opinions_temp', ['id'], unique=False)
    op.create_index(op.f('ix_opinions_temp_nickname'), 'opinions_temp', ['nickname'], unique=False)
    op.create_table('room_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['exercise_rooms.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_participants_id'), 'room_participants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_participants_id'), table_name='room_participants')
    op.drop_table('room_participants')
    op.drop_index(op.f('ix_opinions_temp_nickname'), table_name='opinions_temp')
    op.drop_index(op.f('ix_opinions_temp_id'), table_name='opinions_temp')
    op.drop_index(op.f('ix_opinions_temp_comment_location'), table_name='opinions_temp')
    op.drop_table('opinions_temp')
    op.drop_index(op.f('ix_history_info_id'), table_name='history_info')
    op.drop_table('history_info')
    op.drop_index(op.f('ix_userinfo_id'), table_name='userinfo')
    op.drop_table('userinfo')
    op.drop_index(op.f('ix_tokens_token_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_token_hash'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_opinions_nickname'), table_name='opinions')
    op.drop_index(op.f('ix_opinions_main_comment_mid'), table_name='opinions')
    op.drop_index(op.f('ix_opinions_comment_location'), table_name='opinions')
    op.drop_table('opinions')
    op.drop_index(op.f('ix_exercise_rooms_room_id'), table_name='exercise_rooms')
    op.drop_index(op.f('ix_exercise_rooms_invite_code'), table_name='exercise_rooms')
    op.drop_table('exercise_rooms')
    op.drop_index(op.f('ix_events_temp_uid'), table_name='events_temp')
    op.drop_index(op.f('ix_events_temp_title'), table_name='events_temp')
    op.drop_index(op.f('ix_events_temp_room_id'), table_name='events_temp')
    op.drop_index(op.f('ix_events_temp_publish_time'), table_name='events_temp')
    op.drop_index(op.f('ix_events_temp_nickname'), table_name='events_temp')
    op.drop_index(op.f('ix_events_temp_mid'), table_name='events_temp')
    op.drop_index(op.f('ix_events_temp_event_type'), table_name='events_temp')
    op.drop_index(op.f('ix_events_temp_event_source'), table_name='events_temp')
    op.drop_index(op.f('ix_events_temp_create_time'), table_name='events_temp')
    op.drop_table('events_temp')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_school_name_name'), table_name='school_name')
    op.drop_index(op.f('ix_school_name_id'), table_name='school_name')
    op.drop_table('school_name')
    op.drop_index(op.f('ix_real_events_title'), table_name='real_events')
    op.drop_index(op.f('ix_real_events_room_id'), table_name='real_events')
    op.drop_index(op.f('ix_real_events_real_mid'), table_name='real_events')
    op.drop_index(op.f('ix_real_events_publish_time'), table_name='real_events')
    op.drop_index(op.f('ix_real_events_nickname'), table_name='real_events')
    op.drop_table('real_events')
    op.drop_index(op.f('ix_events_uid'), table_name='events')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_publish_time'), table_name='events')
    op.drop_index(op.f('ix_events_nickname'), table_name='events')
    op.drop_index(op.f('ix_events_mid'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_source'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
