"""add_relay_status

Revision ID: e6fb43100d5e
Revises: 8cab0d0aa3bd
Create Date: 2024-12-17 15:41:52.627396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fb43100d5e'
down_revision: Union[str, None] = '8cab0d0aa3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinions_temp', sa.Column('comment_rating', sa.Text(), nullable=True))
    op.add_column('opinions_temp', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('real_events', sa.Column('is_ai', sa.Boolean(), nullable=True))
    op.add_column('real_events', sa.Column('retweets', sa.Integer(), nullable=True))
    op.add_column('real_events', sa.Column('comment_num', sa.Integer(), nullable=True))
    op.add_column('real_events', sa.Column('star_num', sa.Integer(), nullable=True))
    op.add_column('real_events', sa.Column('is_hot', sa.Boolean(), nullable=True))
    op.add_column('real_events', sa.Column('event_type', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_real_events_event_type'), 'real_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_real_events_event_type'), table_name='real_events')
    op.drop_column('real_events', 'event_type')
    op.drop_column('real_events', 'is_hot')
    op.drop_column('real_events', 'star_num')
    op.drop_column('real_events', 'comment_num')
    op.drop_column('real_events', 'retweets')
    op.drop_column('real_events', 'is_ai')
    op.drop_column('opinions_temp', 'status')
    op.drop_column('opinions_temp', 'comment_rating')
    # ### end Alembic commands ###
